CREATE TABLE users(
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	PRIMARY KEY(id)
	);
	
CREATE TABLE form(
   id INT NOT NULL AUTO_INCREMENT,
   user_id VARCHAR (100) NOT NULL,
   genre VARCHAR (100) NOT NULL,
   name VARCHAR (100) NOT NULL,
   comment VARCHAR (100) NOT NULL,
   attime TIMESTAMP,
   PRIMARY KEY (id)
);